//
// Created by Nicholas on 2023/9/12.
//

#ifndef DATASTRUCTANDALGORITHMS_ILLEGALPARAMETERVALUE_H
#define DATASTRUCTANDALGORITHMS_ILLEGALPARAMETERVALUE_H

#endif //DATASTRUCTANDALGORITHMS_ILLEGALPARAMETERVALUE_H
